"""empty message

Revision ID: 3e042e768d98
Revises: 7fc14cbdfba4
Create Date: 2026-05-31 19:55:14.044802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e042e768d98'
down_revision: Union[str, Sequence[str], None] = '7fc14cbdfba4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('city_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'city_id')
    # ### end Alembic commands ###
