"""empty message

Revision ID: 51e70c0ebba2
Revises: 3e042e768d98
Create Date: 2026-05-31 20:09:00.390396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51e70c0ebba2'
down_revision: Union[str, Sequence[str], None] = '3e042e768d98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('locations', 'city_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('locations', 'city_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###
