"""add latitude and longitude to schedules

Revision ID: 81bbd8b66fcd
Revises: 91ed44395060
Create Date: 2026-08-17 15:39:57.827471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81bbd8b66fcd'
down_revision: Union[str, Sequence[str], None] = '91ed44395060'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('schedules', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedules', 'longitude')
    op.drop_column('schedules', 'latitude')
    # ### end Alembic commands ###
